version: '2'

services:
 seleniumhub:
  image: selenium/hub
  ports:
    - "4444:4444"

 firefox:
  image: selenium/node-firefox
  depends_on:
    - seleniumhub
  ports:
    - 5900
  links:
    - seleniumhub

 chrome:
  image: selenium/node-chrome
  depends_on:
    - seleniumhub
  ports:
    - 5900
  links:
    - seleniumhub