version: '2'

services:
 nexus:
  build: ./nexus
  ports:
    - "8181:8081"

 jenkins:
  build: ./jenkins
  ports:
    - "8888:8080"
  links:
    - nexus
    - gitlab
    - sonar
    - sonardb
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /opt/jenkins:/var/lib/jenkins
  depends_on:
    - nexus
    - gitlab
    - sonar
    - sonardb
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: ./sonar
  ports:
   - "9000:9000"
   - "5432:5432"
  links:    
    - sonardb
  depends_on:    
    - sonardb  
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar

 sonardb:
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data

 gitlab:
  image: gitlab/gitlab-ce:8.14.4-ce.0
  restart: always
  ports:
    - "8000:80"
    - "22222:22"
  volumes:
    - /opt/gitlab/config:/etc/gitlab
    - /opt/gitlab/logs:/var/log/gitlab
    - /opt/gitlab/data:/var/opt/gitlab
